objects:
  common:
    initial_pos_range: [ 2.9, 1.0 ,0.91, 2.9, 1.0 ,0.91]
    initial_ori_range: [0, 0, 0, 0, 0, 0]
    soft_reset_pos_range: [ 2.9, 1.0 ,0.91, 2.9, 1.0 ,0.91]
    soft_reset_ori_range: [0, 0, 0, 0, 0, 0]
    scale: [1.5, 1.5, 1.5]

  fluid_items:
    common:
    usd: ["XXX.usd"]
    num_per_env: 1
    random: True
    interaction_with_object: False

    fluid_items_1:
      visual:
        scale: [1.3,1.3,1.3]
        container_scale: [1.0,1.0,1.0]
        visual_material:
          material_usd_folder: []

      pos: [2.5082827, -1.89822, 0.72]   # 2.6182827, -1.88822, 0.66  2.4942827, -1.94822, 0.68
      physics:
        type: "fluid"
        particle_system:
          particle_contact_offset: 0.0025
          contact_offset: 0.0025
          rest_offset: 0.0024
          fluid_rest_offset: 0.0015
          solid_rest_offset: 0.001
          max_velocity: 0.5
          smoothing: False
          anisotropy: False
          isosurface: True

        particle_material:
          adhesion: null
          adhesion_offset_scale: null
          cohesion: 0.01
          particle_adhesion_scale: null
          particle_friction_scale: null
          drag: null
          lift: null
          friction: 0.1
          damping: 0.99
          gravity_scale: 1.0
          viscosity: 0.0091
          vorticity_confinement: null
          surface_tension: 0.0074
          density: null
          cfl_coefficient: null

        fluid_volumn: 1.3

bowl:
  common:
    initial_pos_range: [ 1.61, -2.3, 0.545, 1.61, -2.3, 0.545] 
    initial_ori_range: [0, 0, 0, 0, 0, 0]
    soft_reset_pos_range: [ 1.61, -2.3 ,0.545, 1.61, -2.3,0.545]
    soft_reset_ori_range: [0, 0, 0, 0, 0, 0]
    scale: [1.0, 1.0, 1.0]