objects:
  common:
    initial_pos_range: [ 1.25459, -2.5692, 0.03, 1.08459, -2.3592, 0.03] # [1.20459, -2.5692, 0.01, 1.25459, -2.6092, 0.01]
    initial_ori_range: [0, 0, 0, 0,0, 0]
    soft_reset_pos_range: [1.25459, -2.5692, 0.03, 1.08459, -2.3592, 0.03]
    soft_reset_ori_range: [0, 0, 0, 0,0, 0]
    scale: [1.0, 1.0, 1.0]

  fluid_items:
    common:
    usd: ["XXX.usd"]
    num_per_env: 1
    random: True
    interaction_with_object: False

    fluid_items_1:
      visual:
        scale: [1.0,1.0,1.0]
        container_scale: [1.0,1.0,1.0]
        visual_material:
          material_usd_folder: [
            # "/home/glzn/IsaacLab/lehome/source/lehome/lehome/assets/object/fluid/material/Textiles/Linen_Beige.mdl",
            # "/home/glzn/IsaacLab/lehome/source/lehome/lehome/assets/object/fluid/material/Textiles/Linen_White.mdl",
            # "/home/glzn/IsaacLab/lehome/source/lehome/lehome/assets/object/fluid/material/Textiles/Linen_Blue.mdl",
            # "/home/glzn/IsaacLab/lehome/source/lehome/lehome/assets/object/fluid/material/Textiles/Leather_Black.mdl",
            "/home/glzn/IsaacLab/lehome/source/lehome/lehome/assets/object/fluid/material/Textiles/Leather_Brown.mdl",
            # "/home/glzn/IsaacLab/lehome/source/lehome/lehome/assets/object/fluid/material/Textiles/Leather_Black.mdl",
            # "/home/glzn/IsaacLab/lehome/source/lehome/lehome/assets/object/fluid/material/Natural/Water_Opaque.mdl",
            # "/home/glzn/IsaacLab/lehome/source/lehome/lehome/assets/object/fluid/material/Natural/Water.mdl",
          ]

      # pos: [0.0, 0.0, 1.2]
      # ori: [0.0,0.0,0.0]
      physics:
        type: "fluid"
        particle_system:
          particle_contact_offset: 0.005
          contact_offset: 0.005
          rest_offset: 0.00495
          fluid_rest_offset: 0.00297
          solid_rest_offset: 0.00297
          max_velocity: 2.5
          smoothing: False
          anisotropy: False
          isosurface: True

        particle_material:
          adhesion: null
          adhesion_offset_scale: null
          cohesion: 0.01
          particle_adhesion_scale: null
          particle_friction_scale: null
          drag: null
          lift: null
          friction: 0.1
          damping: 0.99
          gravity_scale: 1.0
          viscosity: 0.0091
          vorticity_confinement: null
          surface_tension: 0.0074
          density: null
          cfl_coefficient: null

        fluid_volumn: 1